tap 'cantino/mcfly'

if OS.linux?
   tap 'gromgit/fuse'
end

if OS.mac?
    # tap 'homebrew/bundle'
    # tap 'homebrew/cask'
    # tap 'homebrew/core'
    tap 'homebrew/cask-fonts'
    cask 'firefox'
    cask 'font-fira-code'
    cask 'font-hack-nerd-font'
    cask 'font-fira-code-nerd-font'
    cask 'font-fira-mono-nerd-font'
    cask 'google-chrome'
    cask 'inkscape'
    brew 'reattach-to-user-namespace'
    cask 'iterm2'
    cask 'karabiner-elements'
    cask 'qlmarkdown'
    cask 'vlc'
    cask 'steam'
end

brew 'automake'
brew 'bat'
brew 'coreutils'
brew 'ctags'
brew 'findutils'
brew 'fzf'
brew 'gh'
brew 'git'
brew 'git-delta'
brew 'git-extras'
brew 'highlight'
brew 'lame'
brew 'mcfly'
brew 'neovim'
brew 'openssl'
brew 'podofo'
brew 'python3'
brew 'ranger'
brew 'readline'
brew 'ripgrep'
brew 'spaceman-diff'
brew 'tidy-html5'
brew 'tmux'
brew 'tree'
brew 'x264'
brew 'xvid'
brew 'youtube-dl'
brew 'zsh'
brew 'ffmpeg'
brew 'rename'
brew 'zsh-vi-mode'
