$script_cmder = <<-SCRIPT
choco uninstall -y 7zip 7zip.install
choco install -y cmder 7zip
SCRIPT

$script_cmderdev = <<-SCRIPT
call c:\\tools\\cmder\\vendor\\init.bat
cd /d c:\\Users\\Vagrant
git clone https://github.com/cmderdev/cmder cmderdev
cd cmderdev
git remote add upstream  https://github.com/cmderdev/cmder
git pull upstream master
copy C:\\Tools\\Cmder\\Cmder.exe .\\
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "win10" do |win10|
    win10.vm.hostname = 'win10'
    win10.vm.box = "windows_10"

    # win10.vm.network :private_network, ip: "192.168.56.101"

    win10.vm.provider :virtualbox do |v|
      # v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--name", "win10"]
      v.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["setextradata", :id, "GUI/ScaleFactor", "1.75"]
    end
  end

  config.vm.define "win10_vs2022" do |win10_vs2022|
    win10_vs2022.vm.hostname = 'win10-vs2022'
    win10_vs2022.vm.box = "gusztavvargadr/visual-studio"

    # win10-vs2022.vm.network :private_network, ip: "192.168.56.102"

    win10_vs2022.vm.provider :virtualbox do |v|
      # v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--name", "win10-vs2022"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end

    # config.winrm.timeout = 21600

    # config.vm.provision "shell" do |s|
    #   s.path = "scripts/cmder.ps1"
    # end

    # config.vm.provision "shell" do |s|
    #   s.path = "scripts/cmderdev.cmd"
    # end

    # config.vm.provision "shell" do |s|
    #   s.path = "scripts/vsc2022_uninstall.ps1"
    # end

    # config.vm.provision "shell" do |s|
    #   s.path = "scripts/vsc2022_install.ps1"
    # end
  end

  config.vm.provision "shell", inline: $script_cmder
  config.vm.provision "shell", inline: $script_cmderdev
  # config.winrm.timeout = 21600

  # config.vm.provision "shell" do |s|
  #   s.path = "scripts/cmder.ps1"
  # end

  # config.vm.provision "shell" do |s|
  #   s.path = "scripts/cmderdev.cmd"
  # end

  # config.vm.provision "shell" do |s|
  #   s.path = "scripts/vsc2022_install.ps1"
  # end
end
